version: "3.2"

services:
  mondrian:
    image: lumapps/mondrian
    build: .
    volumes:
      - type: bind
        source: ./Candidates
        target: /src/Candidates
      - type: bind
        source: ./Transformed
        target: /src/Transformed
    ports:
      - "6916:6916"
    restart: unless-stopped
